version: '3.8'

services:
    db:
        image: mysql:5.7
        container_name: laravel_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: laravel_user
            DB_PASSWORD: laravel_password

volumes:
    db_data:
