spring:
  datasource:
    url: jdbc:postgresql://db:5432/mydb
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

mlservice:
  url: http://mlservice:5000 